// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCxd1r9VCGx2NmXilDdLdgCqs5w7kmqmo',
    appId: '1:963034045749:web:138add73ec40296aa5c07c',
    messagingSenderId: '963034045749',
    projectId: 'katkote-84ef9',
    authDomain: 'katkote-84ef9.firebaseapp.com',
    storageBucket: 'katkote-84ef9.appspot.com',
    measurementId: 'G-YF6XEYME3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0JerJFRvoe6-c9YhxHXZ5ruIw2gk-6Bw',
    appId: '1:963034045749:android:bc654d49cdff06e3a5c07c',
    messagingSenderId: '963034045749',
    projectId: 'katkote-84ef9',
    storageBucket: 'katkote-84ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2gjKqCUGwFhzgLMNqP-Lj6yNXvGxx3Lc',
    appId: '1:963034045749:ios:5a8ae55bab6a7538a5c07c',
    messagingSenderId: '963034045749',
    projectId: 'katkote-84ef9',
    storageBucket: 'katkote-84ef9.appspot.com',
    iosBundleId: 'com.example.katkote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2gjKqCUGwFhzgLMNqP-Lj6yNXvGxx3Lc',
    appId: '1:963034045749:ios:d838d9c9e552a55da5c07c',
    messagingSenderId: '963034045749',
    projectId: 'katkote-84ef9',
    storageBucket: 'katkote-84ef9.appspot.com',
    iosBundleId: 'com.example.katkote.RunnerTests',
  );
}
